image: "redoxos/redoxer"

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git
format:
  cache:
    paths:
      - cargo/
      - target/
  script:
    - rustup default nightly
    - rustup component add rustfmt
    - cargo +nightly fmt --all -- --check

linux:
  image: 'rust:1.35.0'
  cache:
    paths:
      - cargo/
      - target/
  script:
    - cargo check --features=piston
    - FULL=1 make tests

linux:stable:
  cache:
    paths:
      - cargo/
      - target/
  script:
    - cargo check --features=piston
    - TOOLCHAIN= make tests

redox:
  before_script:
    - apt-get update -qq
    - apt-get install -qq build-essential curl git
    - git clone --single-branch --branch=add-redox-support --depth=1 https://github.com/AdminXVII/nix
    - mkdir .cargo
    - echo 'paths = [ "nix" ]' >> .cargo/config
    - cargo clean
  script:
    - redoxer test

link-check:
  image: hrektts/mdbook
  before_script:
    - apt-get update -qq
    - apt-get install -qq libssl-dev pkg-config build-essential curl git
    - (test -x $HOME/.cargo/bin/mdbook-linkcheck || cargo install mdbook-linkcheck)
  script:
  - make manual
  - mdbook build manual

pages:
  image: hrektts/mdbook
  stage: deploy
  script:
  - make manual
  - mdbook build manual
  - mv manual/book/html public
  artifacts:
    paths:
    - public
  only:
  - master

compare-benchmarks:
  image: rustlang/rust:nightly
  stage: test
  when: manual
  allow_failure: true
  except: [master]
  script:
    - apt-get update && apt-get install -y build-essential libboost-dev jq bc
    - sh ./ci/run_benchmark.sh
  artifacts:
    reports:
      junit: target/report.xml
    paths: [target/criterion]
