image: "redoxos/redoxer"

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git libssl libssl-dev
cache:
  paths:
    - cargo/
    - target/
    # Redox only:
    - prefix/
    - rust/

format:
  script:
    - rustup default nightly
    - rustup component add rustfmt
    - cargo +nightly fmt --all -- --check

linux:
  image: 'rust:1.35.0'
  script:
    - cargo build
    - FULL=1 make tests

linux:stable:
  script:
    - cargo build
    - TOOLCHAIN= make tests

redox:
  script:
    - redoxer build

pages:
  image: hrektts/mdbook
  stage: deploy
  script:
  - make manual
  - mdbook build -d ../public manual
  artifacts:
    paths:
    - public
  only:
  - master

compare-benchmarks:
  image: rustlang/rust:nightly
  stage: test
  when: manual
  allow_failure: true
  except: [master]
  script:
    - apt-get update && apt-get install -y build-essential libboost-dev jq bc
    - sh ./ci/run_benchmark.sh
  artifacts:
    reports:
      junit: target/report.xml
    paths: [target/criterion]
